### ISSUE TITLE
AttributeError: 'Iterator' object has no attribute 'item_to_value' in datastore/query.py page_iterator.Page

### ISSUE THREAD

**Issue by bialoglowy** [GoogleCloudPlatform/google-cloud-datastore#200]
I'm getting the following AttributeError error in datastore/query.py:

```
Traceback (most recent call last):
  File "/env/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/env/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/env/lib/python3.6/site-packages/falcon/api.py", line 244, in __call__
    responder(req, resp, **params)
  File "/home/vmagent/app/sec_api/rest/resources/project.py", line 1281, in on_get
    raise ex
  File "/home/vmagent/app/sec_api/rest/resources/project.py", line 1243, in on_get
    _results = self.resource.stats()
  File "/home/vmagent/app/sec_api/resources/project.py", line 98, in wrapper
    return f(*args, **kwds)
  File "/home/vmagent/app/sec_api/resources/project.py", line 816, in stats
    _all = self.storage.all(keys_only=False)
  File "/home/vmagent/app/sec_api/storage.py", line 1207, in all
    keys_only=keys_only)
  File "/home/vmagent/app/sec_api/storage.py", line 125, in wrapper
    raise _ex
  File "/home/vmagent/app/sec_api/storage.py", line 108, in wrapper
    return f(*args, **kwds)
  File "/home/vmagent/app/sec_api/storage.py", line 1232, in _get_all
    for entity in query_iter:
  File "/env/lib/python3.6/site-packages/google/api_core/page_iterator.py", line 186, in _items_iter
    for page in self._page_iter(increment=False):
  File "/env/lib/python3.6/site-packages/google/api_core/page_iterator.py", line 217, in _page_iter
    page = self._next_page()
  File "/env/lib/python3.6/site-packages/google/cloud/datastore/query.py", line 518, in _next_page
    return page_iterator.Page(self, entity_pbs, self.item_to_value)
AttributeError: 'Iterator' object has no attribute 'item_to_value'
```

It happens in the following code:
```
    def all(self, exclude_deleted=True):
        _query = self.client.query(kind=self.kind)
        _all = []
        query_iter = _query.fetch()
        for entity in query_iter:
            _all.append(entity)
```

Application is deployed on Google App Engine with the following requirements.txt:

```
google-gax==0.16.0
google-cloud==0.32.0
google-cloud-core==0.28.1
google-cloud-datastore==1.6.0
google-cloud-pubsub==0.33.0
google-cloud-storage==1.8.0

```

**Comment by daniiln** [comment]
experiencing the same issus after updated to the latest datastore library
```
from google.cloud import datastore
kind = 'blah'
datastore_client = datastore.Client()
query = datastore_client.query(kind=kind)
queryset = list(query.fetch())
```

**Comment by dkavraal** [comment]
Dropped to 1.5.0, then it works.

**Comment by bialoglowy** [comment]
I dropped to 1.50, with the following versions and still experience the same issue:

google-gax==0.15.16
google-cloud==0.32.0
google-cloud-core==0.28.0
google-cloud-datastore==1.5.0
google-cloud-pubsub==0.33.0
google-cloud-storage==1.7.0

**Comment by bialoglowy** [comment]
Correct, it works on google-cloud-datastore==1.5.0.

**Comment by wsh** [comment]
Hey there! I'm sorry you're experiencing this issue, but the driver you're having issues with is part of [google-cloud-python](https://github.com/GoogleCloudPlatform/google-cloud-python/tree/master/datastore). The Python driver in this repo (package name `googledatastore`) is totally separate. Please re-file this issue there and the google-cloud-python team will investigate. Sorry for the confusing situation.

**Comment by wsh** [comment]
This issue was moved to GoogleCloudPlatform/google-cloud-python#5169

**Comment by weiwuprojects** [comment]
For future reference, I had this issue and resolved it by removing google-api-core from my requirements.

My requirements.txt looked like below and the error did not appear after removing google-api-core and running a pip install. My best guess is that google-cloud-datastore or storage installs another version of google-api-core and that caused a conflict.

Flask==1.0.2
protobuf==3.6.0
gunicorn==19.8.1
google-cloud-datastore==1.7.3
google-cloud-storage==1.14.0
google-api-core==1.9.0 
grpcio>=1.2.0
